#
# This file is auto-generated. DO NOT EDIT
# Generated by: autospec.py
# Using build pattern: R
# autospec version: v5
# autospec commit: c02b2fe
#
Name     : R-gh
Version  : 1.4.1
Release  : 49
URL      : https://cran.r-project.org/src/contrib/gh_1.4.1.tar.gz
Source0  : https://cran.r-project.org/src/contrib/gh_1.4.1.tar.gz
Summary  : 'GitHub' 'API'
Group    : Development/Tools
License  : MIT
Requires: R-cli
Requires: R-gitcreds
Requires: R-glue
Requires: R-httr2
Requires: R-ini
Requires: R-jsonlite
Requires: R-lifecycle
Requires: R-rlang
BuildRequires : R-cli
BuildRequires : R-gitcreds
BuildRequires : R-glue
BuildRequires : R-httr2
BuildRequires : R-ini
BuildRequires : R-jsonlite
BuildRequires : R-lifecycle
BuildRequires : R-rlang
BuildRequires : buildreq-R
# Suppress stripping binaries
%define __strip /bin/true
%define debug_package %{nil}

%description
# gh
<!-- badges: start -->
[![R-CMD-check](https://github.com/r-lib/gh/workflows/R-CMD-check/badge.svg)](https://github.com/r-lib/gh/actions)
[![Codecov test
coverage](https://codecov.io/gh/r-lib/gh/branch/main/graph/badge.svg)](https://app.codecov.io/gh/r-lib/gh?branch=main)
[![](https://www.r-pkg.org/badges/version/gh)](https://www.r-pkg.org/pkg/gh)
[![CRAN Posit mirror
downloads](https://cranlogs.r-pkg.org/badges/gh)](https://www.r-pkg.org/pkg/gh)
[![R-CMD-check](https://github.com/r-lib/gh/actions/workflows/R-CMD-check.yaml/badge.svg)](https://github.com/r-lib/gh/actions/workflows/R-CMD-check.yaml)
<!-- badges: end -->

%prep
%setup -q -n gh
pushd ..
cp -a gh buildavx2
popd
pushd ..
cp -a gh buildavx512
popd

%build
export http_proxy=http://127.0.0.1:9/
export https_proxy=http://127.0.0.1:9/
export no_proxy=localhost,127.0.0.1,0.0.0.0
export LANG=C.UTF-8
export SOURCE_DATE_EPOCH=1711730021

%install
export SOURCE_DATE_EPOCH=1711730021
rm -rf %{buildroot}
LANG=C.UTF-8
CFLAGS="$CLEAR_INTERMEDIATE_CFLAGS -O3 -flto -fno-semantic-interposition "
FCFLAGS="$CLEAR_INTERMEDIATE_FFLAGS -O3 -flto -fno-semantic-interposition "
FFLAGS="$CLEAR_INTERMEDIATE_FFLAGS -O3 -flto -fno-semantic-interposition "
CXXFLAGS="$CLEAR_INTERMEDIATE_CXXFLAGS -O3 -flto -fno-semantic-interposition "
AR=gcc-ar
RANLIB=gcc-ranlib
LDFLAGS="$CLEAR_INTERMEDIATE_LDFLAGS  -Wl,-z -Wl,relro"
mkdir -p %{buildroot}/usr/lib64/R/library
mkdir -p %{buildroot}-v3/usr/lib64/R/library
mkdir -p %{buildroot}-v4/usr/lib64/R/library
mkdir -p %{buildroot}-va/usr/lib64/R/library

mkdir -p ~/.R
echo "CFLAGS = $CFLAGS -march=x86-64-v3 -ftree-vectorize -mno-vzeroupper" > ~/.R/Makevars
echo "FFLAGS = $FFLAGS -march=x86-64-v3 -ftree-vectorize -mno-vzeroupper " >> ~/.R/Makevars
echo "CXXFLAGS = $CXXFLAGS -march=x86-64-v3 -ftree-vectorize -mno-vzeroupper " >> ~/.R/Makevars
R CMD INSTALL  --install-tests --use-LTO --built-timestamp=${SOURCE_DATE_EPOCH} --data-compress=none --compress=none --build  -l %{buildroot}-v3/usr/lib64/R/library .
echo "CFLAGS = $CFLAGS -march=x86-64-v4 -mprefer-vector-width=512 -ftree-vectorize  -mno-vzeroupper " > ~/.R/Makevars
echo "FFLAGS = $FFLAGS -march=x86-64-v4 -mprefer-vector-width=512 -ftree-vectorize  -mno-vzeroupper " >> ~/.R/Makevars
echo "CXXFLAGS = $CXXFLAGS -march=x86-64-v4 -mprefer-vector-width=512 -ftree-vectorize -mno-vzeroupper " >> ~/.R/Makevars
R CMD INSTALL --preclean  --install-tests --use-LTO --no-test-load --data-compress=none --compress=none --built-timestamp=${SOURCE_DATE_EPOCH} --build  -l %{buildroot}-v4/usr/lib64/R/library .
echo "CFLAGS = $CFLAGS -ftree-vectorize " > ~/.R/Makevars
echo "FFLAGS = $FFLAGS -ftree-vectorize " >> ~/.R/Makevars
echo "CXXFLAGS = $CXXFLAGS -ftree-vectorize " >> ~/.R/Makevars
R CMD INSTALL --preclean  --use-LTO --install-tests --data-compress=none --compress=none --built-timestamp=${SOURCE_DATE_EPOCH} --build  -l %{buildroot}/usr/lib64/R/library .
%{__rm} -rf %{buildroot}%{_datadir}/R/library/R.css
%check
export LANG=C.UTF-8
export http_proxy=http://127.0.0.1:9/
export https_proxy=http://127.0.0.1:9/
export no_proxy=localhost,127.0.0.1,0.0.0.0
export _R_CHECK_FORCE_SUGGESTS_=false
R CMD check --no-manual --no-examples --no-codoc . || :

/usr/bin/elf-move.py avx2 %{buildroot}-v3 %{buildroot} %{buildroot}/usr/share/clear/filemap/filemap-%{name}
/usr/bin/elf-move.py avx512 %{buildroot}-v4 %{buildroot} %{buildroot}/usr/share/clear/filemap/filemap-%{name}

%files
%defattr(-,root,root,-)
/usr/lib64/R/library/gh/DESCRIPTION
/usr/lib64/R/library/gh/INDEX
/usr/lib64/R/library/gh/LICENSE
/usr/lib64/R/library/gh/Meta/Rd.rds
/usr/lib64/R/library/gh/Meta/features.rds
/usr/lib64/R/library/gh/Meta/hsearch.rds
/usr/lib64/R/library/gh/Meta/links.rds
/usr/lib64/R/library/gh/Meta/nsInfo.rds
/usr/lib64/R/library/gh/Meta/package.rds
/usr/lib64/R/library/gh/Meta/vignette.rds
/usr/lib64/R/library/gh/NAMESPACE
/usr/lib64/R/library/gh/NEWS.md
/usr/lib64/R/library/gh/R/gh
/usr/lib64/R/library/gh/R/gh.rdb
/usr/lib64/R/library/gh/R/gh.rdx
/usr/lib64/R/library/gh/WORDLIST
/usr/lib64/R/library/gh/doc/index.html
/usr/lib64/R/library/gh/doc/managing-personal-access-tokens.R
/usr/lib64/R/library/gh/doc/managing-personal-access-tokens.Rmd
/usr/lib64/R/library/gh/doc/managing-personal-access-tokens.html
/usr/lib64/R/library/gh/help/AnIndex
/usr/lib64/R/library/gh/help/aliases.rds
/usr/lib64/R/library/gh/help/figures/lifecycle-archived.svg
/usr/lib64/R/library/gh/help/figures/lifecycle-defunct.svg
/usr/lib64/R/library/gh/help/figures/lifecycle-deprecated.svg
/usr/lib64/R/library/gh/help/figures/lifecycle-experimental.svg
/usr/lib64/R/library/gh/help/figures/lifecycle-maturing.svg
/usr/lib64/R/library/gh/help/figures/lifecycle-questioning.svg
/usr/lib64/R/library/gh/help/figures/lifecycle-soft-deprecated.svg
/usr/lib64/R/library/gh/help/figures/lifecycle-stable.svg
/usr/lib64/R/library/gh/help/figures/lifecycle-superseded.svg
/usr/lib64/R/library/gh/help/gh.rdb
/usr/lib64/R/library/gh/help/gh.rdx
/usr/lib64/R/library/gh/help/paths.rds
/usr/lib64/R/library/gh/html/00Index.html
/usr/lib64/R/library/gh/html/R.css
/usr/lib64/R/library/gh/tests/testthat.R
/usr/lib64/R/library/gh/tests/testthat/_snaps/gh.md
/usr/lib64/R/library/gh/tests/testthat/_snaps/gh_request.md
/usr/lib64/R/library/gh/tests/testthat/_snaps/gh_response.md
/usr/lib64/R/library/gh/tests/testthat/_snaps/gh_whoami.md
/usr/lib64/R/library/gh/tests/testthat/_snaps/pagination.md
/usr/lib64/R/library/gh/tests/testthat/_snaps/print.md
/usr/lib64/R/library/gh/tests/testthat/helper-offline.R
/usr/lib64/R/library/gh/tests/testthat/helper.R
/usr/lib64/R/library/gh/tests/testthat/test-gh.R
/usr/lib64/R/library/gh/tests/testthat/test-gh_rate_limit.R
/usr/lib64/R/library/gh/tests/testthat/test-gh_request.R
/usr/lib64/R/library/gh/tests/testthat/test-gh_response.R
/usr/lib64/R/library/gh/tests/testthat/test-gh_token.R
/usr/lib64/R/library/gh/tests/testthat/test-gh_whoami.R
/usr/lib64/R/library/gh/tests/testthat/test-git.R
/usr/lib64/R/library/gh/tests/testthat/test-mock-repos.R
/usr/lib64/R/library/gh/tests/testthat/test-old-templates.R
/usr/lib64/R/library/gh/tests/testthat/test-pagination.R
/usr/lib64/R/library/gh/tests/testthat/test-print.R
/usr/lib64/R/library/gh/tests/testthat/test-spelling.R
/usr/lib64/R/library/gh/tests/testthat/test-utils.R
